[opener]
edit = [
  { run = '${EDITOR:-nvim} %s', block = true, desc = "Edit in terminal", for = "unix" },
]
image-workspace = [
  { run = "~/.local/bin/open-image-workspace %s1", orphan = true, desc = "Abrir imagen eligiendo workspace", for = "linux" },
]

[open]
prepend_rules = [
  { url = "*.md", use = "edit" },
  { url = "*.markdown", use = "edit" },
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image-workspace" },
]
