# Sin transparencias entre ventana activa/inactiva:
# el foco visual queda solo en bordes/colores definidos por i3.
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = true;

# Sin animaciones de aparición/desaparición.
fading = false;

# Sombras
shadow = false;

# Redondeo de bordes
corner-radius = 0;

# Sin sombra para notificaciones Dunst
shadow-exclude = [
  "class_g = 'Dunst'"
];
